/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserDashboardRouteImport } from './routes/user-dashboard'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminloginRouteImport } from './routes/adminlogin'
import { Route as AdminDashboardUserAnalyticsRouteImport } from './routes/admin-dashboard-user-analytics'
import { Route as AdminDashboardSystemSettingsRouteImport } from './routes/admin-dashboard-system-settings'
import { Route as AdminDashboardPaymentTrackingRouteImport } from './routes/admin-dashboard-payment-tracking'
import { Route as AdminDashboardOrderManagementRouteImport } from './routes/admin-dashboard-order-management'
import { Route as AdminDashboardImageUploadRouteImport } from './routes/admin-dashboard-image-upload'
import { Route as AdminDashboardFoodManagementRouteImport } from './routes/admin-dashboard-food-management'
import { Route as AdminDashboardDeliveryManagementRouteImport } from './routes/admin-dashboard-delivery-management'
import { Route as AdminDashboardChangePasswordRouteImport } from './routes/admin-dashboard-change-password'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user-dashboard',
  path: '/user-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminloginRoute = AdminloginRouteImport.update({
  id: '/adminlogin',
  path: '/adminlogin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardUserAnalyticsRoute =
  AdminDashboardUserAnalyticsRouteImport.update({
    id: '/admin-dashboard-user-analytics',
    path: '/admin-dashboard-user-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardSystemSettingsRoute =
  AdminDashboardSystemSettingsRouteImport.update({
    id: '/admin-dashboard-system-settings',
    path: '/admin-dashboard-system-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardPaymentTrackingRoute =
  AdminDashboardPaymentTrackingRouteImport.update({
    id: '/admin-dashboard-payment-tracking',
    path: '/admin-dashboard-payment-tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardOrderManagementRoute =
  AdminDashboardOrderManagementRouteImport.update({
    id: '/admin-dashboard-order-management',
    path: '/admin-dashboard-order-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardImageUploadRoute =
  AdminDashboardImageUploadRouteImport.update({
    id: '/admin-dashboard-image-upload',
    path: '/admin-dashboard-image-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardFoodManagementRoute =
  AdminDashboardFoodManagementRouteImport.update({
    id: '/admin-dashboard-food-management',
    path: '/admin-dashboard-food-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardDeliveryManagementRoute =
  AdminDashboardDeliveryManagementRouteImport.update({
    id: '/admin-dashboard-delivery-management',
    path: '/admin-dashboard-delivery-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardChangePasswordRoute =
  AdminDashboardChangePasswordRouteImport.update({
    id: '/admin-dashboard-change-password',
    path: '/admin-dashboard-change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-change-password': typeof AdminDashboardChangePasswordRoute
  '/admin-dashboard-delivery-management': typeof AdminDashboardDeliveryManagementRoute
  '/admin-dashboard-food-management': typeof AdminDashboardFoodManagementRoute
  '/admin-dashboard-image-upload': typeof AdminDashboardImageUploadRoute
  '/admin-dashboard-order-management': typeof AdminDashboardOrderManagementRoute
  '/admin-dashboard-payment-tracking': typeof AdminDashboardPaymentTrackingRoute
  '/admin-dashboard-system-settings': typeof AdminDashboardSystemSettingsRoute
  '/admin-dashboard-user-analytics': typeof AdminDashboardUserAnalyticsRoute
  '/adminlogin': typeof AdminloginRoute
  '/cart': typeof CartRoute
  '/change-password': typeof ChangePasswordRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/user-dashboard': typeof UserDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-change-password': typeof AdminDashboardChangePasswordRoute
  '/admin-dashboard-delivery-management': typeof AdminDashboardDeliveryManagementRoute
  '/admin-dashboard-food-management': typeof AdminDashboardFoodManagementRoute
  '/admin-dashboard-image-upload': typeof AdminDashboardImageUploadRoute
  '/admin-dashboard-order-management': typeof AdminDashboardOrderManagementRoute
  '/admin-dashboard-payment-tracking': typeof AdminDashboardPaymentTrackingRoute
  '/admin-dashboard-system-settings': typeof AdminDashboardSystemSettingsRoute
  '/admin-dashboard-user-analytics': typeof AdminDashboardUserAnalyticsRoute
  '/adminlogin': typeof AdminloginRoute
  '/cart': typeof CartRoute
  '/change-password': typeof ChangePasswordRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/user-dashboard': typeof UserDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-change-password': typeof AdminDashboardChangePasswordRoute
  '/admin-dashboard-delivery-management': typeof AdminDashboardDeliveryManagementRoute
  '/admin-dashboard-food-management': typeof AdminDashboardFoodManagementRoute
  '/admin-dashboard-image-upload': typeof AdminDashboardImageUploadRoute
  '/admin-dashboard-order-management': typeof AdminDashboardOrderManagementRoute
  '/admin-dashboard-payment-tracking': typeof AdminDashboardPaymentTrackingRoute
  '/admin-dashboard-system-settings': typeof AdminDashboardSystemSettingsRoute
  '/admin-dashboard-user-analytics': typeof AdminDashboardUserAnalyticsRoute
  '/adminlogin': typeof AdminloginRoute
  '/cart': typeof CartRoute
  '/change-password': typeof ChangePasswordRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/user-dashboard': typeof UserDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/admin-dashboard-change-password'
    | '/admin-dashboard-delivery-management'
    | '/admin-dashboard-food-management'
    | '/admin-dashboard-image-upload'
    | '/admin-dashboard-order-management'
    | '/admin-dashboard-payment-tracking'
    | '/admin-dashboard-system-settings'
    | '/admin-dashboard-user-analytics'
    | '/adminlogin'
    | '/cart'
    | '/change-password'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/signup'
    | '/user-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/admin-dashboard-change-password'
    | '/admin-dashboard-delivery-management'
    | '/admin-dashboard-food-management'
    | '/admin-dashboard-image-upload'
    | '/admin-dashboard-order-management'
    | '/admin-dashboard-payment-tracking'
    | '/admin-dashboard-system-settings'
    | '/admin-dashboard-user-analytics'
    | '/adminlogin'
    | '/cart'
    | '/change-password'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/signup'
    | '/user-dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/admin-dashboard-change-password'
    | '/admin-dashboard-delivery-management'
    | '/admin-dashboard-food-management'
    | '/admin-dashboard-image-upload'
    | '/admin-dashboard-order-management'
    | '/admin-dashboard-payment-tracking'
    | '/admin-dashboard-system-settings'
    | '/admin-dashboard-user-analytics'
    | '/adminlogin'
    | '/cart'
    | '/change-password'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/signup'
    | '/user-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDashboardChangePasswordRoute: typeof AdminDashboardChangePasswordRoute
  AdminDashboardDeliveryManagementRoute: typeof AdminDashboardDeliveryManagementRoute
  AdminDashboardFoodManagementRoute: typeof AdminDashboardFoodManagementRoute
  AdminDashboardImageUploadRoute: typeof AdminDashboardImageUploadRoute
  AdminDashboardOrderManagementRoute: typeof AdminDashboardOrderManagementRoute
  AdminDashboardPaymentTrackingRoute: typeof AdminDashboardPaymentTrackingRoute
  AdminDashboardSystemSettingsRoute: typeof AdminDashboardSystemSettingsRoute
  AdminDashboardUserAnalyticsRoute: typeof AdminDashboardUserAnalyticsRoute
  AdminloginRoute: typeof AdminloginRoute
  CartRoute: typeof CartRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  UserDashboardRoute: typeof UserDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-dashboard': {
      id: '/user-dashboard'
      path: '/user-dashboard'
      fullPath: '/user-dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminlogin': {
      id: '/adminlogin'
      path: '/adminlogin'
      fullPath: '/adminlogin'
      preLoaderRoute: typeof AdminloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-user-analytics': {
      id: '/admin-dashboard-user-analytics'
      path: '/admin-dashboard-user-analytics'
      fullPath: '/admin-dashboard-user-analytics'
      preLoaderRoute: typeof AdminDashboardUserAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-system-settings': {
      id: '/admin-dashboard-system-settings'
      path: '/admin-dashboard-system-settings'
      fullPath: '/admin-dashboard-system-settings'
      preLoaderRoute: typeof AdminDashboardSystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-payment-tracking': {
      id: '/admin-dashboard-payment-tracking'
      path: '/admin-dashboard-payment-tracking'
      fullPath: '/admin-dashboard-payment-tracking'
      preLoaderRoute: typeof AdminDashboardPaymentTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-order-management': {
      id: '/admin-dashboard-order-management'
      path: '/admin-dashboard-order-management'
      fullPath: '/admin-dashboard-order-management'
      preLoaderRoute: typeof AdminDashboardOrderManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-image-upload': {
      id: '/admin-dashboard-image-upload'
      path: '/admin-dashboard-image-upload'
      fullPath: '/admin-dashboard-image-upload'
      preLoaderRoute: typeof AdminDashboardImageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-food-management': {
      id: '/admin-dashboard-food-management'
      path: '/admin-dashboard-food-management'
      fullPath: '/admin-dashboard-food-management'
      preLoaderRoute: typeof AdminDashboardFoodManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-delivery-management': {
      id: '/admin-dashboard-delivery-management'
      path: '/admin-dashboard-delivery-management'
      fullPath: '/admin-dashboard-delivery-management'
      preLoaderRoute: typeof AdminDashboardDeliveryManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-change-password': {
      id: '/admin-dashboard-change-password'
      path: '/admin-dashboard-change-password'
      fullPath: '/admin-dashboard-change-password'
      preLoaderRoute: typeof AdminDashboardChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDashboardChangePasswordRoute: AdminDashboardChangePasswordRoute,
  AdminDashboardDeliveryManagementRoute: AdminDashboardDeliveryManagementRoute,
  AdminDashboardFoodManagementRoute: AdminDashboardFoodManagementRoute,
  AdminDashboardImageUploadRoute: AdminDashboardImageUploadRoute,
  AdminDashboardOrderManagementRoute: AdminDashboardOrderManagementRoute,
  AdminDashboardPaymentTrackingRoute: AdminDashboardPaymentTrackingRoute,
  AdminDashboardSystemSettingsRoute: AdminDashboardSystemSettingsRoute,
  AdminDashboardUserAnalyticsRoute: AdminDashboardUserAnalyticsRoute,
  AdminloginRoute: AdminloginRoute,
  CartRoute: CartRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  UserDashboardRoute: UserDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
